package cn.edu.xmu.oomall.payment.mapper.generator;

import cn.edu.xmu.oomall.payment.mapper.generator.po.BusinessPo;
import cn.edu.xmu.oomall.payment.mapper.generator.po.BusinessPoExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface BusinessPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @Delete({
        "delete from payment_business",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @Insert({
        "insert into payment_business (`name`, `creator_id`, ",
        "`creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, ",
        "`gmt_modified`)",
        "values (#{name,jdbcType=VARCHAR}, #{creatorId,jdbcType=BIGINT}, ",
        "#{creatorName,jdbcType=VARCHAR}, #{modifierId,jdbcType=BIGINT}, ",
        "#{modifierName,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(BusinessPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @InsertProvider(type=BusinessPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(BusinessPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @SelectProvider(type=BusinessPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<BusinessPo> selectByExample(BusinessPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `name`, `creator_id`, `creator_name`, `modifier_id`, `modifier_name`, ",
        "`gmt_create`, `gmt_modified`",
        "from payment_business",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    BusinessPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BusinessPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") BusinessPo row, @Param("example") BusinessPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BusinessPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") BusinessPo row, @Param("example") BusinessPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @UpdateProvider(type=BusinessPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BusinessPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_business
     *
     * @mbg.generated
     */
    @Update({
        "update payment_business",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BusinessPo row);
}