package cn.edu.xmu.oomall.payment.mapper.generator;

import cn.edu.xmu.oomall.payment.mapper.generator.po.DivRefundTransPo;
import cn.edu.xmu.oomall.payment.mapper.generator.po.DivRefundTransPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DivRefundTransPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @Delete({
        "delete from payment_div_refund_trans",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @Insert({
        "insert into payment_div_refund_trans (`out_no`, `trans_no`, ",
        "`amount`, `status`, `success_time`, ",
        "`adjust_id`, `adjust_name`, ",
        "`adjust_time`, `refund_trans_id`, ",
        "`div_pay_trans_id`, `creator_id`, ",
        "`creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, ",
        "`gmt_modified`)",
        "values (#{outNo,jdbcType=VARCHAR}, #{transNo,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=BIGINT}, #{status,jdbcType=TINYINT}, #{successTime,jdbcType=TIMESTAMP}, ",
        "#{adjustId,jdbcType=BIGINT}, #{adjustName,jdbcType=VARCHAR}, ",
        "#{adjustTime,jdbcType=TIMESTAMP}, #{refundTransId,jdbcType=BIGINT}, ",
        "#{divPayTransId,jdbcType=BIGINT}, #{creatorId,jdbcType=BIGINT}, ",
        "#{creatorName,jdbcType=VARCHAR}, #{modifierId,jdbcType=BIGINT}, ",
        "#{modifierName,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(DivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @InsertProvider(type=DivRefundTransPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(DivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @SelectProvider(type=DivRefundTransPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_no", property="outNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="trans_no", property="transNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="adjust_id", property="adjustId", jdbcType=JdbcType.BIGINT),
        @Result(column="adjust_name", property="adjustName", jdbcType=JdbcType.VARCHAR),
        @Result(column="adjust_time", property="adjustTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="refund_trans_id", property="refundTransId", jdbcType=JdbcType.BIGINT),
        @Result(column="div_pay_trans_id", property="divPayTransId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<DivRefundTransPo> selectByExample(DivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `out_no`, `trans_no`, `amount`, `status`, `success_time`, `adjust_id`, ",
        "`adjust_name`, `adjust_time`, `refund_trans_id`, `div_pay_trans_id`, `creator_id`, ",
        "`creator_name`, `modifier_id`, `modifier_name`, `gmt_create`, `gmt_modified`",
        "from payment_div_refund_trans",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="out_no", property="outNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="trans_no", property="transNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.BIGINT),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="success_time", property="successTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="adjust_id", property="adjustId", jdbcType=JdbcType.BIGINT),
        @Result(column="adjust_name", property="adjustName", jdbcType=JdbcType.VARCHAR),
        @Result(column="adjust_time", property="adjustTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="refund_trans_id", property="refundTransId", jdbcType=JdbcType.BIGINT),
        @Result(column="div_pay_trans_id", property="divPayTransId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    DivRefundTransPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DivRefundTransPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") DivRefundTransPo row, @Param("example") DivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DivRefundTransPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") DivRefundTransPo row, @Param("example") DivRefundTransPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @UpdateProvider(type=DivRefundTransPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DivRefundTransPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_div_refund_trans
     *
     * @mbg.generated
     */
    @Update({
        "update payment_div_refund_trans",
        "set `out_no` = #{outNo,jdbcType=VARCHAR},",
          "`trans_no` = #{transNo,jdbcType=VARCHAR},",
          "`amount` = #{amount,jdbcType=BIGINT},",
          "`status` = #{status,jdbcType=TINYINT},",
          "`success_time` = #{successTime,jdbcType=TIMESTAMP},",
          "`adjust_id` = #{adjustId,jdbcType=BIGINT},",
          "`adjust_name` = #{adjustName,jdbcType=VARCHAR},",
          "`adjust_time` = #{adjustTime,jdbcType=TIMESTAMP},",
          "`refund_trans_id` = #{refundTransId,jdbcType=BIGINT},",
          "`div_pay_trans_id` = #{divPayTransId,jdbcType=BIGINT},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(DivRefundTransPo row);
}