package cn.edu.xmu.webfluxdemo.mapper;

import cn.edu.xmu.webfluxdemo.model.po.FlashSaleItemPo;
import cn.edu.xmu.webfluxdemo.model.po.FlashSaleItemPoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FlashSaleItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int insert(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int insertSelective(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    List<FlashSaleItemPo> selectByExample(FlashSaleItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    FlashSaleItemPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlashSaleItemPo record);
}