package cn.edu.xmu.webfluxdemo.mapper;

import cn.edu.xmu.webfluxdemo.model.po.GoodsSkuPo;
import cn.edu.xmu.webfluxdemo.model.po.GoodsSkuPoExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GoodsSkuPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    int insert(GoodsSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    int insertSelective(GoodsSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    List<GoodsSkuPo> selectByExample(GoodsSkuPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    GoodsSkuPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsSkuPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_goods_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsSkuPo record);
}