package cn.edu.xmu.oomall.payment.mapper.generator.po;

import lombok.ToString;

import java.time.LocalDateTime;

@ToString
public class PayTransPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.out_no
     *
     * @mbg.generated
     */
    private String outNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.trans_no
     *
     * @mbg.generated
     */
    private String transNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.success_time
     *
     * @mbg.generated
     */
    private LocalDateTime successTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.adjust_id
     *
     * @mbg.generated
     */
    private Long adjustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.adjust_name
     *
     * @mbg.generated
     */
    private String adjustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.adjust_time
     *
     * @mbg.generated
     */
    private LocalDateTime adjustTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.sp_openid
     *
     * @mbg.generated
     */
    private String spOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.time_expire
     *
     * @mbg.generated
     */
    private LocalDateTime timeExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.time_begin
     *
     * @mbg.generated
     */
    private LocalDateTime timeBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.shop_channel_id
     *
     * @mbg.generated
     */
    private Long shopChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.business_id
     *
     * @mbg.generated
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.creator_name
     *
     * @mbg.generated
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.modifier_id
     *
     * @mbg.generated
     */
    private Long modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.modifier_name
     *
     * @mbg.generated
     */
    private String modifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_pay_trans.prepay_id
     *
     * @mbg.generated
     */
    private String prepayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.id
     *
     * @return the value of payment_pay_trans.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.id
     *
     * @param id the value for payment_pay_trans.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.out_no
     *
     * @return the value of payment_pay_trans.out_no
     *
     * @mbg.generated
     */
    public String getOutNo() {
        return outNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.out_no
     *
     * @param outNo the value for payment_pay_trans.out_no
     *
     * @mbg.generated
     */
    public void setOutNo(String outNo) {
        this.outNo = outNo == null ? null : outNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.trans_no
     *
     * @return the value of payment_pay_trans.trans_no
     *
     * @mbg.generated
     */
    public String getTransNo() {
        return transNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.trans_no
     *
     * @param transNo the value for payment_pay_trans.trans_no
     *
     * @mbg.generated
     */
    public void setTransNo(String transNo) {
        this.transNo = transNo == null ? null : transNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.amount
     *
     * @return the value of payment_pay_trans.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.amount
     *
     * @param amount the value for payment_pay_trans.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.status
     *
     * @return the value of payment_pay_trans.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.status
     *
     * @param status the value for payment_pay_trans.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.success_time
     *
     * @return the value of payment_pay_trans.success_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.success_time
     *
     * @param successTime the value for payment_pay_trans.success_time
     *
     * @mbg.generated
     */
    public void setSuccessTime(LocalDateTime successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.adjust_id
     *
     * @return the value of payment_pay_trans.adjust_id
     *
     * @mbg.generated
     */
    public Long getAdjustId() {
        return adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.adjust_id
     *
     * @param adjustId the value for payment_pay_trans.adjust_id
     *
     * @mbg.generated
     */
    public void setAdjustId(Long adjustId) {
        this.adjustId = adjustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.adjust_name
     *
     * @return the value of payment_pay_trans.adjust_name
     *
     * @mbg.generated
     */
    public String getAdjustName() {
        return adjustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.adjust_name
     *
     * @param adjustName the value for payment_pay_trans.adjust_name
     *
     * @mbg.generated
     */
    public void setAdjustName(String adjustName) {
        this.adjustName = adjustName == null ? null : adjustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.adjust_time
     *
     * @return the value of payment_pay_trans.adjust_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAdjustTime() {
        return adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.adjust_time
     *
     * @param adjustTime the value for payment_pay_trans.adjust_time
     *
     * @mbg.generated
     */
    public void setAdjustTime(LocalDateTime adjustTime) {
        this.adjustTime = adjustTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.sp_openid
     *
     * @return the value of payment_pay_trans.sp_openid
     *
     * @mbg.generated
     */
    public String getSpOpenid() {
        return spOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.sp_openid
     *
     * @param spOpenid the value for payment_pay_trans.sp_openid
     *
     * @mbg.generated
     */
    public void setSpOpenid(String spOpenid) {
        this.spOpenid = spOpenid == null ? null : spOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.time_expire
     *
     * @return the value of payment_pay_trans.time_expire
     *
     * @mbg.generated
     */
    public LocalDateTime getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.time_expire
     *
     * @param timeExpire the value for payment_pay_trans.time_expire
     *
     * @mbg.generated
     */
    public void setTimeExpire(LocalDateTime timeExpire) {
        this.timeExpire = timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.time_begin
     *
     * @return the value of payment_pay_trans.time_begin
     *
     * @mbg.generated
     */
    public LocalDateTime getTimeBegin() {
        return timeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.time_begin
     *
     * @param timeBegin the value for payment_pay_trans.time_begin
     *
     * @mbg.generated
     */
    public void setTimeBegin(LocalDateTime timeBegin) {
        this.timeBegin = timeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.shop_channel_id
     *
     * @return the value of payment_pay_trans.shop_channel_id
     *
     * @mbg.generated
     */
    public Long getShopChannelId() {
        return shopChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.shop_channel_id
     *
     * @param shopChannelId the value for payment_pay_trans.shop_channel_id
     *
     * @mbg.generated
     */
    public void setShopChannelId(Long shopChannelId) {
        this.shopChannelId = shopChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.business_id
     *
     * @return the value of payment_pay_trans.business_id
     *
     * @mbg.generated
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.business_id
     *
     * @param businessId the value for payment_pay_trans.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.creator_id
     *
     * @return the value of payment_pay_trans.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.creator_id
     *
     * @param creatorId the value for payment_pay_trans.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.creator_name
     *
     * @return the value of payment_pay_trans.creator_name
     *
     * @mbg.generated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.creator_name
     *
     * @param creatorName the value for payment_pay_trans.creator_name
     *
     * @mbg.generated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.modifier_id
     *
     * @return the value of payment_pay_trans.modifier_id
     *
     * @mbg.generated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.modifier_id
     *
     * @param modifierId the value for payment_pay_trans.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.modifier_name
     *
     * @return the value of payment_pay_trans.modifier_name
     *
     * @mbg.generated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.modifier_name
     *
     * @param modifierName the value for payment_pay_trans.modifier_name
     *
     * @mbg.generated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.gmt_create
     *
     * @return the value of payment_pay_trans.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.gmt_create
     *
     * @param gmtCreate the value for payment_pay_trans.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.gmt_modified
     *
     * @return the value of payment_pay_trans.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.gmt_modified
     *
     * @param gmtModified the value for payment_pay_trans.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_pay_trans.prepay_id
     *
     * @return the value of payment_pay_trans.prepay_id
     *
     * @mbg.generated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_pay_trans.prepay_id
     *
     * @param prepayId the value for payment_pay_trans.prepay_id
     *
     * @mbg.generated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }
}