package cn.edu.xmu.javaee.goodsdemo.mapper.generator;

import cn.edu.xmu.javaee.goodsdemo.mapper.po.GoodsPo;
import cn.edu.xmu.javaee.goodsdemo.mapper.po.GoodsPoExample;
import java.util.List;

public interface GoodsPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    int insert(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    int insertSelective(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    List<GoodsPo> selectByExample(GoodsPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    GoodsPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsPo row);
}