package cn.edu.xmu.javaee.goodsdemo.mapper.generator;

import cn.edu.xmu.javaee.goodsdemo.mapper.po.OnSalePo;
import cn.edu.xmu.javaee.goodsdemo.mapper.po.OnSalePoExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OnSalePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insert(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int insertSelective(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    List<OnSalePo> selectByExample(OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    OnSalePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OnSalePo row, @Param("example") OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OnSalePo row, @Param("example") OnSalePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OnSalePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_onsale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OnSalePo row);
}