management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          service-base-url: http://localhost:8080
server:
  port: 8080
company:
  boss:
    drive: haval
